openapi: '3.0.3'
info:
  title: API para el MENU de nuestro restaurante
  version: '1.0'
  description: |
    # Título
    API para las distintas recetas.
    Cuenta con operaciones CRUD para las recetas e ingredientes y su
    disponibilidad en la semana 
    
tags:
  - name: receta
    description: recetas de plato de comida
paths:
  /recetas:
    get:
      summary: Obtener la receta
      operationId: getComida
      tags:
        - receta
      responses:
        '200':
          description: OK/ACK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/recetas'
    post:
      summary: Añadir una receta
      operationId: addReceta
      tags:
        - receta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/recetas'
      responses:
        '201':
          description: Receta añadida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/info_nuevo_elemento'
        default:
          description: Error al añadir receta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /recetas/{id}:
    get:
      summary: Obtener datos de una receta dada
      operationId: getRecetaFromId
      tags:
        - receta
      responses:
        '200':
          description: ACK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recetas'
            application/xml:
              schema:
                $ref: '#/components/schemas/recetas'
        default:
          description: Error al obtener la receta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      parameters:
        - $ref: '#/components/parameters/id'
    put:
      summary: Modificar datos de una receta concreta
      operationId: updateReceta
      tags:
        - receta
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '201':
          description: Ok
        default:
          description: Error al obtener la receta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comida_edit'
    delete:
      summary: Eliminar una receta del menú
      description: TODO
      operationId: deleteReceta
      tags:
        - receta
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: ACK
        default:
          description: Error al obtener la receta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    id:
      name: id
      in: path
      description: ID de la receta
      required: true
      schema:
        $ref: '#/components/schemas/id'
  schemas:
    id:
      type: integer
      minimum: 1
    error:
      type: object
      properties:
        descripcion:
          type: string
        codigo:
          type: integer
      example: {
        "descripcion": "Input error",
        "codigo": 400}
    info_nuevo_elemento:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
      example: {"id": 7}
    recetas:
      type: array
      items:
        $ref: '#/components/schemas/receta'
    receta:
      allOf:
        - $ref: '#/components/schemas/receta_edit'
        - required:
          - titulo
          - ingredientes
          - instrucciones
          - imagen
      example:
        {"receta": "Lentejas_con_chorizo",
        "titulo":
          {"titulo": "lentejas",},
        "ingredientes": [{"nombre": "lentejas"},{"nombre": "zanahorias"},{"nombre": "chorizo"}, {"nombre": "guisantes"},],
        "instrucciones": "Añadimos las lentejas, la hoja de laurel y las patatas, chascándolas con el cuchillo, y cocemos un par de minutos. Cubrimos con abundante agua fría y cocemos (mejor tapadas) durante 40-50 minutos o hasta que estén tiernas. Si se vieran muy secas, añadimos más agua durante el proceso. Calentamos un chorro de aceite en una sartén, añadimos el pimentón y retiramos inmediatamente del fuego para evitar que se queme. Incorporamos a la cacerola con las lentejas, removemos y cocemos cinco minutos más. Servimos bien calientes."
         "imagen":""
      }
    receta_edit:
      type: object
      additionalProperties: false
      minProperties: 1
      properties:
        receta:
          type: string
        titulo:
          type: string
        ingredientes:
          $ref: '#/components/schemas/array_ingredientes'
        instrucciones:
          type: string
        imagen:
          type: string
      example:
        {"receta": "Lentejas_con_chorizo"}
    array_ingredientes:
      type: array
      items:
        $ref: '#/components/schemas/ingrediente'
    ingrediente:
      type: object
      required:
        - nombre
      properties:
        nombre:
          type: string
      example: {"nombre": "Queso"}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/luislazarraga/SistemasWebPractica
  - description: Basic Server
    url: /api/v1